tweet_stats/main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [ 
    path('', views.dayplot, name='dayplot'),
    path('terms', views.terms, name='terms'),
    path('privacy', views.privacy, name='privacy'),
    path('plotfilter/', views.plotfilter, name='plotfilter'),
    path('plotfilter_for_week/', views.plotfilter_for_week, name='plotfilter_for_week'),
    path('tweets/', views.tweets_analysis, name='tweets_analysis'),
    path('tweets/<int:days>/', views.tweets_analysis, name='tweets_analysis_refresh'),
    path('tweets_detail/<str:sub_category>/', views.tweets_detail, name='tweets_detail'),

    #Reply feature

    path('reply/<int:tweet_ID>/', views.ReplyTweet, name="reply_tweet"),
    path('reply/<str:sub_category>/', views.ReplyPanel, name="reply_panel"),
    path('reply/<str:sub_category>/testjs', views.TestJs, name="testjs"),
    path('reply/<str:sub_category>/reply_with_image', views.TestJs, name="reply_with_image"),

        
    #db Migration. Used only once.

    path('tweets/migrate/days/', views.migrate_tweet_day, name='migrate_tweet_day'),
    path('tweets/migrate/weeks/', views.migrate_tweet_week, name='migrate_tweet_weeks'),
    

]

tweet_stats/project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls import url, include


urlpatterns = [
    path('', include('main_app.urls', namespace='main_app')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]

""" if settings.DEBUG:
   import debug_toolbar
   urlpatterns += [
       url(r'^__debug__/', include(debug_toolbar.urls)),
   ] """

tweet_stats/main_app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from .models import Category, SubCategory, CategoryDetail, SubCategoryDetail,Tweets
from .main import RetrieveTweetstoCSV
from .extract_text import *
from .replies import *
from .reply_to_tweet import *
from django.db.utils import IntegrityError
import time, datetime
from datetime import date, timedelta
from django.db.models import Count
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import tweepy
from django.core.files.storage import default_storage
import random, string

# Create your views here.

def terms(request):
    return render(request, 'main_app/terms.html', {})

def privacy(request):
    return render(request, 'main_app/privacy.html', {})

def tweets_analysis(request, *args, **kwargs):

    context = {}
    
    days = kwargs.get("days", None)

    if days is not None:
        start_date = datetime.date.today() - timedelta(days=days) 
        finish_date = datetime.date.today() + timedelta(days=1)
    
    categories = Category.objects.all()

    for category in categories:
 
        subcategories = SubCategory.objects.filter(category = category)

        for subcategory in subcategories:

            if start_date is not None and finish_date is not None:
      
                TweetList = TweetToList('#' + subcategory.name, start_date = start_date, finish_date = finish_date)

                AddSentimentToTweetList(TweetList)

                for tweet in TweetList:
                    try: 
                        new_tweet = Tweets.objects.create(category = category, sub_category = subcategory, tweet_ID = tweet[0], tweet_username = tweet[1], tweet_date = tweet[2], tweet_day = tweet[2].date(), tweet_content = tweet[3], tweet_URL = tweet[4], tweet_sentiment = tweet[5], tweet_week = int(str(tweet[2].year) + str(tweet[2].isocalendar()[1])))        
                        new_tweet.save() 
                    except IntegrityError:
                        print("Tweet with ID" + str(tweet[0]) + "already exists.")
                    except :
                        print("An unknow error has occurred.")



    messages.success(request, "Tweets successfuly updated!!")

    return render(request, 'main_app/tweets.html')


def tweets_detail(request, sub_category):
    subcategory = request.GET.get('sub_category.name', None)
    context = {}
    tweetlist = Tweets.objects.filter(sub_category__name = sub_category)
    context['tweetlist'] = tweetlist        
    return render(request, 'main_app/tweets_detail.html', context)

def dayplot(request):
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    tweets_type = ["All", "Total positive", "Total negative", "Total alarming"]
    date_list_for_table = []
    days = 7
    weeks = 4

    try : 

        latesttweet = Tweets.objects.latest("tweet_date")

        for i in range(days):
            date_list_for_table.append(latesttweet.tweet_date.date() - datetime.timedelta(days=i) )

        date_list = date_list_for_table[::-1]

        if Tweets.objects.values('tweet_week').order_by('-tweet_week').annotate(Count("tweet_week")).count() >= weeks:
            weeklist = [Tweets.objects.values('tweet_week').order_by('-tweet_week').annotate(Count("tweet_week"))[x]['tweet_week'] if Tweets.objects.values('tweet_week').order_by('-tweet_week').annotate(Count("tweet_week"))[x]  else 0 for x in
    range (4)][::-1]
        else:
            weeklist = [Tweets.objects.values('tweet_week').order_by('-tweet_week').annotate(Count("tweet_week"))[x]['tweet_week'] if Tweets.objects.values('tweet_week').order_by('-tweet_week').annotate(Count("tweet_week"))[x]  else 0 for x in
    range (Tweets.objects.values('tweet_week').order_by('-tweet_week').annotate(Count("tweet_week")).count())][::-1]

        weeklist = ["Week " + str(x)[4:6] for x in weeklist]

        #Data for Days Plot
        
        chart_data = Tweets.objects.get_tweets_by_category()
        positive_data = Tweets.objects.get_tweets_by_sentiment(sentiment="Positive")
        negative_data = Tweets.objects.get_tweets_by_sentiment(sentiment="Negative")
        alarming_data = Tweets.objects.get_tweets_by_sentiment(sentiment="Alarming")

        #Data for Weeks Plot
        
        chart_data2    = Tweets.objects.get_tweets_by_category_and_weeks()
        positive_data2 = Tweets.objects.get_tweets_by_sentiment_and_weeks(sentiment="Positive")
        negative_data2 = Tweets.objects.get_tweets_by_sentiment_and_weeks(sentiment="Negative")
        alarming_data2 = Tweets.objects.get_tweets_by_sentiment_and_weeks(sentiment="Alarming")

        #Data for Table 

        table_per_day = {}
        for subcategory in SubCategory.objects.all():
            table_per_day[subcategory.name] = {}
            tot_alarming = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_sentiment = "Alarming").aggregate(Count("tweets__tweet_sentiment"))["tweets__tweet_sentiment__count"]
            tot_positive = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_sentiment = "Positive").aggregate(Count("tweets__tweet_sentiment"))["tweets__tweet_sentiment__count"]
            tot_negative = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_sentiment = "Negative").aggregate(Count("tweets__tweet_sentiment"))["tweets__tweet_sentiment__count"]
            tot_tweets = tot_alarming + tot_positive + tot_negative

            if tot_alarming != 0:
                table_per_day[subcategory.name]['alarming'] = round(100*tot_alarming/tot_tweets,2)
            else:
                table_per_day[subcategory.name]['alarming'] = 0
            if tot_positive != 0:
                table_per_day[subcategory.name]['positive'] = round(100*tot_positive/tot_tweets,2)
            else:
                table_per_day[subcategory.name]['positive'] = 0

            if tot_negative != 0:
                table_per_day[subcategory.name]['negative'] = round(100*tot_negative/tot_tweets,2)
            else:
                table_per_day[subcategory.name]['negative'] = 0

            table_per_day[subcategory.name]['dia1'] = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_day = latesttweet.tweet_day).aggregate(Count('tweets__tweet_date'))['tweets__tweet_date__count']
            table_per_day[subcategory.name]['dia2'] = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_day = latesttweet.tweet_day - datetime.timedelta(days=1)).aggregate(Count('tweets__tweet_day'))['tweets__tweet_day__count']
            table_per_day[subcategory.name]['dia3'] = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_day = latesttweet.tweet_day - datetime.timedelta(days=2)).aggregate(Count('tweets__tweet_day'))['tweets__tweet_day__count']
            table_per_day[subcategory.name]['dia4'] = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_day = latesttweet.tweet_day - datetime.timedelta(days=3)).aggregate(Count('tweets__tweet_day'))['tweets__tweet_day__count']
            table_per_day[subcategory.name]['dia5'] = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_day = latesttweet.tweet_day - datetime.timedelta(days=4)).aggregate(Count('tweets__tweet_day'))['tweets__tweet_day__count']
            table_per_day[subcategory.name]['dia6'] = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_day = latesttweet.tweet_day - datetime.timedelta(days=5)).aggregate(Count('tweets__tweet_day'))['tweets__tweet_day__count']
            table_per_day[subcategory.name]['dia7'] = SubCategory.objects.filter(name = subcategory.name, tweets__tweet_day = latesttweet.tweet_day - datetime.timedelta(days=6)).aggregate(Count('tweets__tweet_day'))['tweets__tweet_day__count']

    except:

        date_list = []
        weeklist = []
        table_per_day = []
        positive_data = [] 
        negative_data = [] 
        alarming_data = [] 
        chart_data = [] 
        positive_data2 = [] 
        negative_data2 = [] 
        alarming_data2 = [] 
        chart_data2 = []


    context = {"categories": categories,  "date_list": date_list, 
               "tweets_type": tweets_type, "date_list_for_table" : date_list_for_table, 
               "subcategories": subcategories,  "weeklist" : weeklist, "table_per_day": table_per_day, 
               "chart_data": chart_data, "positive_data": positive_data, "negative_data": negative_data, "alarming_data": alarming_data,
               "chart_data2": chart_data2, "positive_data2": positive_data2, "negative_data2": negative_data2, "alarming_data2": alarming_data2,
               }

    return render(request, 'main_app/days.html', context)

def plotfilter(request):

    """
    Function that filters Week Plot Data for category. Called by Asynocronous JS when plot filters are clicked. Returns 
    new data in form of arrays for total, positive, negative and alarming tweets for a specific category. Chart in the 
    front-end is automatically updated with these data.
    """
    json_response = {'success' : False}

    category = request.GET.get("category", None)
    
    json_response['chart_data']    = Tweets.objects.get_tweets_by_category(category = category, days = 7)
    json_response['positive_data'] = Tweets.objects.get_tweets_by_sentiment(category = category, days = 7, sentiment="Positive")
    json_response['negative_data'] = Tweets.objects.get_tweets_by_sentiment(category = category, days = 7, sentiment="Negative")
    json_response['alarming_data'] = Tweets.objects.get_tweets_by_sentiment(category = category, days = 7, sentiment="Alarming")

    json_response['success'] = True


    return JsonResponse(json_response)

def plotfilter_for_week(request):

    """
    Function that filters Week Plot Data for category. Called by Asynocronous JS when plot filters are clicked. Returns 

tweet_stats/main_app/templates/main_app/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- Nucleo Icons -->
  <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{% static 'assets/css/black-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />
  </head>
  <body>
    <body>
      <!-- Contenido -->
      {% block content %}{% endblock %}
      <!-- Javascript -->
      <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'core/js/main.js' %}"></script>
  </body>
</html>

tweet_stats/main_app/templates/main_app/tweets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <p>
    Tweets updated successfully
    </p>
</body>
</html>

tweet_stats/main_app/templates/main_app/tweets_reply_panel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <title>
    Twitter sentiment analysis
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- Nucleo Icons -->
  <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{% static 'assets/css/black-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />
  
  {% comment %} include math.js {% endcomment %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/7.2.0/math.min.js" integrity="sha512-4VdpCxbABk7wjJb/9z/d3EyibeHwUY0FgHbFO4EiIPVtyyV6llhENCvzRk8SH5D86+Jwm6QLagqRRnEJCd3gJg==" crossorigin="anonymous"></script>

  <!--Add emoticons 
  <script src="https://cdn.tiny.cloud/1/eg3rzac5wir62r0d88d285g4fu7i2iux78667qd4sya1kh3y/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  <script>
  tinymce.init({
    selector: "#custom_text",
    plugins: "emoticons",
    toolbar: "emoticons",
    toolbar_location: "bottom",
    menubar: false
  });
</script> 
-->

</head>

<body class="">
  <div class="wrapper">
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a href="{% url 'main_app:dayplot'%}">Back to Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ml-auto">
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
              </li>
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="{% static 'assets/img/anime3.png' %}" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                {% if request.user.is_authenticated %}

                  <li class="nav-link"><a href="{% url 'logout' %}" class="nav-item dropdown-item">Log out</a></li>
                {% else %}
                  <li class="nav-link"><a href="{% url 'signup' %}" class="nav-item dropdown-item">Register</a></li>
                  <li class="nav-link"><a href="{% url 'login' %}" class="nav-item dropdown-item">Login</a></li>
                {%endif%}


                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->
<!-- Start days table -->
        <div class="row mt-5">
          <div class="col-lg-12 col-md-12">
            <div class="card mt-5">
              <div class="card-header">
                <h4 class="card-title"> </h4>
              </div>
              <div class="card-body">
                <form action="{% url 'main_app:reply_with_image' sub_category %} " method="post" enctype="multipart/form-data"> {% csrf_token %}
                  <div class="mb-3">
                      <input id="negative" type="checkbox" autocomplete="off" name="negative">
                      <label for="negative"> Reply to negative Tweets</label>
                      <input id ="alarming" type="checkbox" autocomplete="off" name="alarming">
                      <label for="alarming"> Reply to alarming Tweets</label>
                      <input id="positive" type="checkbox" autocomplete="off" name="positive">
                      <label for="positive"> Reply to positive Tweets</label>
                  </div>
                  <div class="row mb-4">
                    <div class="col">
                    <input type="submit" id="post_submit" class="btn btn-primary btn-sm disabled" value="Send Reply with new tweets">                      
                        <div>
                          <textarea id="custom_text" name="custom_text" rows="5" cols="70" autocomplete="off" maxlength="280"></textarea>
                        <div>
                          <input id="custom_tweet" type="checkbox"  name="custom_tweet">
                          <label for="custom_tweet">Use Custom tweet</label>
                        </div>
                        </div>
                        <div>
                          <input type="file" id="tweet_file" name="tweet_file">
                          <label for="tweet_file">Upload a picture </label>
                        </div>
                    </div>
                  <div class="col-sm-6">
                    <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
                      {% for type in tweets_type %}
                        <label class="btn btn-sm btn-primary btn-simple {% if type == 'All' %}active{% endif %}" id="tweet{{ forloop.counter0 }}">
                          <input type="radio" name="options" checked>
                          <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">{{ type }}</span>
                        </label> 
                      {% endfor %}
                    </div>
                  </div>
                  </div>
                </form>                  
                  <button id = "send" class="btn btn-primary btn-sm mr-5" > Send Reply with existing tweets</button>
                  <div class="row">
                    <div>
                      <div class="table-responsive">
                        <table class="table tablesorter " id="">
                          <thead class=" text-primary">
                            <tr>
                              <th>
                                Select
                              </th>
                              <th>
                                Tweet ID
                              </th>
                              <th>
                                Tweet Date
                              </th>
                              <th>
                                Tweet Username
                              </th>
                              <th>
                                Tweet Content 
                              </th>
                              <th>
                                Tweet URL
                              </th>
                              <th>
                                Tweet Sentiment
                              </th>
                            </tr>
                          </thead>
                          <tbody>
                            {%for tweet in tweetlist%}
                            <tr>
                              <td>
                                <input type="checkbox" autocomplete="off">
                              </td>
                              <td>
                                {{tweet.tweet_ID}}
                              </td>
                              <td>
                                {{tweet.tweet_date}}
                              </td>
                              <td id="username">
                                {{tweet.tweet_username}}
                              </td>
                              <td>
                                {{tweet.tweet_content}}
                              </td>
                              <td>
                                {{tweet.tweet_URL}}
                              </td>
                              <td>
                                {{tweet.tweet_sentiment}}
                              </td>
                            </tr>
                          {%endfor%}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <ul class="nav">
            <li class="nav-item">
              <a href="javascript:void(0)" class="nav-link">
                Creative Tim
              </a>
            </li>
            <li class="nav-item">
              <a href="javascript:void(0)" class="nav-link">
                About Us
              </a>
            </li>
            <li class="nav-item">
              <a href="javascript:void(0)" class="nav-link">
                Blog
              </a>
            </li>
          </ul>
          <div class="copyright">
            ©
            <script>
              document.write(new Date().getFullYear())
            </script>2018 made with <i class="tim-icons icon-heart-2"></i> by
            <a href="javascript:void(0)" target="_blank">Creative Tim</a> for a better web.
          </div>
        </div>
      </footer>
    </div>
  </div>

  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!--  Google Maps Plugin    -->
  <!-- Place this tag in your head or just before your close body tag. -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/black-dashboard.min.js' %}"></script><!-- Black Dashboard DEMO methods, don't include it in your project! -->

<!-- Tweet Reply logic -->
<!--<script src="{% static 'assets/js/tweets-reply.js' %}"></script> -->
<script>
// Search for selected tweets and save them into the "replies" Array

var replies = []
$("tr").on("click", "input", function(){
        var tweet_ID = $(this).closest('tr').find("td").eq(1).text().replace(/\s/g, '');
        if (($(this).closest('tr').find("td").eq(0).find('input').prop("checked") == true) && replies.includes(tweet_ID) == false )  {
          replies.push(tweet_ID);
          console.log(replies);
          }
        else if (($(this).closest('tr').find("td").eq(0).find('input').prop("checked") == false) && replies.includes(tweet_ID) == true ) {
          replies.splice(replies.indexOf(tweet_ID),1);
          console.log(replies);
        }
        })


//GET REQUEST

$("#send").on("click", function(){
   var url = "testjs" 
  // Pass all selected tweets IDs as a GET parameter, each tweet_ID separated by "-"
    var content = replies.join('-')
    url += "?content=" + content
    if ($("#negative").is(":checked")) {
      url +="&negative=Negative"
    }
    if ($("#positive").is(":checked")) {
      url +="&positive=Positive"
    }
    if ($("#alarming").is(":checked")) {
      url +="&alarming=Alarming"
    }
    if ($("#custom_tweet").is(":checked")) {
      url +="&custom_tweet=custom_tweet"
      var text = encodeURIComponent(document.getElementById("custom_text").value);
      url +="&text=" + text
    }    
    fetch(url, {'credentials':'include'}).then(response => response.json()).then(function(data){
      console.log(data.created)
      console.log(data.arr)
      console.log(data.custom_tweet)
  })
})

$("#post_submit").on("click", function(){
  var content = replies.join('-')
})

$("#custom_tweet").on("click", function(){
  $("#post_submit").toggleClass("disabled");
  $("#send").toggleClass("disabled");
})
</script>

{% comment %} Filtering tweets by category {% endcomment %}
<script src="{% static 'assets/js/TableFilters.js' %}"></script>
</body>

</html>

tweet_stats/main_app/templates/main_app/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Hello World!
</body>
</html>